appName: python-webserver # CHANGEME! lettere minuscole e trattini, no spazi!!
developerName: "Davide Rossi"  # Il tuo nome! o di qualcuno che ti Ã¨ simpatico
serverPort: 9000          # A piacere > 1000

#    Una volta completata la pipeline di CI/CD, potrai raggiungere il tuo sito web navigando su
#   <appName>.demo.k8s.cloudnative.demoreevo.it
